name: ci-build-images

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: blog.e-monkeys.tech Zola ssg custom image build and push
        id: docker_build_rustlang_custom
        uses: docker/build-push-action@v2
        with:
          context: ./blog
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/e-monkeys-blog:2.0
      - name: docs.e-monkeys.tech Mdbook custom image build and push
        id: docker_build_blackarch_custom
        uses: docker/build-push-action@v2
        with:
          context: ./docs
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/e-monkeys-docs:latest